# Generated by Django 4.2.4 on 2023-08-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_created_at_note_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tittle',
            new_name='title',
        ),
    ]
